### ISSUE TITLE
wrong error messages retreiving records by name

### ISSUE THREAD

**Issue by xh3b4sd** [pearkes/cloudflare#3]
I just saw some weird log outputs and I wondered why my code tries to destroy record that often. I found a simple logging error here:
- https://github.com/pearkes/cloudflare/blob/b6d679e928c9a54766d6f164bb17dfb57500b896/record.go#L277
- https://github.com/pearkes/cloudflare/blob/b6d679e928c9a54766d6f164bb17dfb57500b896/record.go#L314

The proper error message should be like 

``` go
return nil, fmt.Errorf("Error retreiving record: %s", err)
```

**Comment by pearkes** [comment]
Fixed, thanks!
